name: Build and Deploy
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@v2.0.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: ninoseki/ninoseki.github.io
          TARGET_BRANCH: master
          BUILD_SCRIPT: npm install -g npm@8 && npm install && npm run docs:build && git config --global --add safe.directory "*"
          BUILD_DIR: docs/.vuepress/dist/
